global:
  scrape_interval: 20s
  scrape_timeout: 10s

scrape_configs:
  - job_name: sadeem
    metrics_path: /metrics
    static_configs:
      - targets:
        # Hardcoded endpoints
        - prometheus:9090
  
  - job_name: node
    static_configs:
    - targets:
      # Hardcoded endpoints
       - node-exporter:9100